# -*- coding: utf-8 -*-
"""DNN_comparision1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVrNvcMzwautUGvsF2wrnTpYH7te001_
"""

import os
import sys
import time
import math

import torch
import torch.optim as optim
import torch.nn as nn
import torch.nn.init as init
import numpy as np
import numpy as np
import pandas as pd
from sklearn.cross_decomposition import CCA

## Network structure

class NN(nn.Module):
    def __init__(self, input_size, output_size, num_layers, hidden_units):
        super(NN, self).__init__()
        self.act=nn.Tanh()

        self.input_size = input_size
        self.output_size = output_size
        self.num_layers = num_layers
        self.hidden_units = hidden_units

        ### Define the input layer
        self.input_layer = nn.Linear(input_size, hidden_units)

        ## Define hidden layers (without Batch Norm)
        self.hidden_layers = nn.ModuleList([
            nn.Linear(hidden_units, hidden_units) for _ in range(num_layers - 1)
        ])

        # Define the output layer
        self.output_layer = nn.Linear(hidden_units, output_size)

    def forward(self, x):
        # Input layer
        x = self.act(self.input_layer(x))

        # Hidden layers
        for layer in self.hidden_layers:
            x = self.act(layer(x))

        # Output layer
        x = self.output_layer(x)

        return x

def custom_weight_init(m):
    if isinstance(m, nn.Linear):
        m.weight.data = 0.5*torch.tensor(np.random.choice([-2, -1, 0, 1, 2], size=m.weight.shape).astype(np.float32))
        m.bias.data = torch.normal(mean=0.0, std=0.02, size=m.bias.shape)


## For CC calculation

def first_d_eigenvectors(matrix, d):
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)

    # Sort the eigenvalues in descending order and get the indices
    sorted_indices = np.argsort(eigenvalues)[::-1]

    # Get the indices of the first d eigenvalues
    top_d_indices = sorted_indices[:d]

    # Get the corresponding eigenvectors to form the eigenmatrix
    first_d_vec = eigenvectors[:, top_d_indices]

    return first_d_vec

def d_eigenvectors(matrix, d):
    eigenvalues, eigenvectors = np.linalg.eigh(matrix)

    # Sort the eigenvalues in descending order and get the indices
    sorted_indices = np.argsort(eigenvalues)[::-1]

    # Get the indices of the first d eigenvalues
    top_d_indices = sorted_indices[d-1]

    # Get the corresponding eigenvectors to form the eigenmatrix
    first_d_vec= eigenvectors[:, top_d_indices].reshape(p,1)

    return first_d_vec


def cc_calculation(deep_f,index_d,number_k):
    D_true=d_eigenvectors(true_feature.detach().numpy(),index_d)
    D_narrow=first_d_eigenvectors(deep_f.detach().cpu().numpy(),number_k)
    T_c, W_c = cca.fit_transform(D_true, D_narrow)

    return np.corrcoef(T_c[:, 0], W_c[:, 0])[0, 1]

cca = CCA(n_components=1)

hiddens=[2]

true_indices = [1, 2, 3, 4, 5]
subspace_dims = [1, 2, 3, 4, 5, 10]


cc = {
    (i, k): np.zeros(5)
    for i in true_indices
    for k in subspace_dims
}

for hidden in hiddens:

  narrow_trainMSE=np.zeros(5)
  narrow_testMSE=np.zeros(5)
  narrow_evalue=np.zeros((5,20))
  true_eig=np.zeros((5,20))

  for seed in range(5):

    torch.random.manual_seed(seed)
    np.random.seed(seed)

    batch_size =100
    p=20
    # n=50000 # or 500
    n=500
    true_net = NN(input_size=p, output_size=1, num_layers=2, hidden_units=5) #.cuda()
    true_net.apply(custom_weight_init)

    true_feature=torch.matmul(true_net.input_layer.weight.data.T,true_net.input_layer.weight.data)

    X=torch.randn(n,p)
    y=true_net(X).clone().data+torch.randn(n,1)*0.1



    X_test=torch.randn(1000,p)
    y_test=true_net(X_test).clone().data+torch.randn(1000,1)*0.1

    ## Narrow DNN

    narrow_net = NN(input_size=p, output_size=1, num_layers=2, hidden_units=5).cuda()


    ## Wide DNN

    wide_net = NN(input_size=p, output_size=1, num_layers=2, hidden_units=1000).cuda()

    from torch.utils.data import DataLoader, TensorDataset


    # Create a Dataset and DataLoader
    dataset = TensorDataset(X.cuda(), y.cuda())
    data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Define the loss function and the optimizer
    criterion = nn.MSELoss()
    optimizer = optim.SGD(narrow_net.parameters(), lr=0.01, momentum=0.9)

    # Training loop
    if n==50000:
      num_epochs = 500
    if n==500:
      num_epochs=10000
    for epoch in range(num_epochs):

        for batch_X, batch_y in data_loader:

            # Forward pass
            outputs = narrow_net(batch_X)
            loss = criterion(outputs, batch_y)
            optimizer.zero_grad()

            loss.backward()
            optimizer.step()

        if (epoch + 1) %1000 == 0:
            narrow_feature=torch.matmul(narrow_net.input_layer.weight.data.T,narrow_net.input_layer.weight.data)
            print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')
            print("test MSE:", criterion(y_test.cuda(),narrow_net(X_test.cuda())).detach().cpu().numpy())

            # first_d=1
            # D_true=d_eigenvectors(true_feature.detach().numpy(),first_d)
            # D_narrow=first_d_eigenvectors(narrow_feature.detach().cpu().numpy(),1)

            # T_c, W_c = cca.fit_transform(D_true, D_narrow)
            # print(np.corrcoef(T_c[:, 0], W_c[:, 0])[0, 1])

    narrow_feature=torch.matmul(narrow_net.input_layer.weight.data.T,narrow_net.input_layer.weight.data)

    for i in true_indices:
        for k in subspace_dims:
            cc[(i, k)][seed] = cc_calculation(narrow_feature, i, k)


    narrow_trainMSE[seed]=  criterion(y.cuda(),narrow_net(X.cuda())).detach().cpu().numpy()
    narrow_testMSE[seed]=  criterion(y_test.cuda(),narrow_net(X_test.cuda())).detach().cpu().numpy()

    e_values, e_vectors = np.linalg.eigh(narrow_feature.detach().cpu().numpy())
    narrow_evalue[seed,:]=np.sort(e_values)[::-1]

    true_e_values, true_e_vectors = np.linalg.eigh(true_feature.detach().numpy())


    true_eig[seed,:]=np.sort(true_e_values)[::-1]

## Eigen comparison

print(np.round(np.mean(true_eig[:,:5],axis=0),2))
print(np.round(np.std(true_eig[:,:5],axis=0)/np.sqrt(5),2))

print(np.round(np.mean(narrow_evalue[:,:5],axis=0),2))
print(np.round(np.std(narrow_evalue[:,:5],axis=0)/np.sqrt(5),2))

### CC calculation

def mean_se(x):
    x = np.asarray(x)
    return np.mean(x), np.std(x) / np.sqrt(len(x))


def format_mean_se(x, digits=3):
    m, se = mean_se(x)
    return f"{m:.{digits}f} ({se:.{digits}f})"



cc_rows = []

for i in true_indices:
    for k in subspace_dims:
        cc_rows.append({
            "True eigenvector": i,
            "Learned eigenspace": f"1:{k}",
            "Notation": rf"rho_{{{i},1:{k}}}",
            "Mean (SE)": format_mean_se(cc[(i, k)], digits=3),
        })

cc_table = pd.DataFrame(cc_rows)

print("\n=== Canonical correlation results ===")
print(cc_table.to_string(index=False))

## Train, Test MSE

print(np.mean(narrow_trainMSE))
print(np.std(narrow_trainMSE)/np.sqrt(5))

print(np.mean(narrow_testMSE))
print(np.std(narrow_testMSE)/np.sqrt(5))